<?php

use App\Models\StaffingCompany\Personnel;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class PersonnelTableSeeder extends Seeder
{
    public function run()
    {
        Personnel::create([
            'salutation' => 'Mr',
            'initials' => 'al',
            'first_name' => 'Ali',
            'last_name' => 'Raza',
            'dob' => '2023-01-01',
            'social_security_number' => '123',
            'date_service' => '2023-01-01',
            'telephone' => '090078601',
            'mobile' => '00000',
            'mobile2' => '00000',
            'mobile3' => '00000',
            'email' => 'abcd@gmail.com',
            'password' => Hash::make(123456),
            'vca_certificate' => 0,
            'own_car' => 0,
            'function_id' => 1,
            'id_type' => 'ssss',
            'id_number' => 'ssss',
            'id_expiry' => '2023-02-02',
            'nationality' => 'USA',
            'address' => 'USA',
            'postcode' => '02',
            'city' => 'NYC',
            'employ_agency_id' => 1,
            'employment_agency_note' => 'Nothing',
            'rate_per_hour' => '200',
            'cost_per_hour' => '10',
            'personnel_dates' => '2023-01-01',
            'active' => 1,
        ]);

        Personnel::create([
            'salutation' => 'Mr',
            'initials' => 'al',
            'first_name' => 'Haseb',
            'last_name' => 'KHan',
            'dob' => '2023-01-01',
            'social_security_number' => '44444',
            'date_service' => '2023-01-01',
            'telephone' => '090078601',
            'mobile' => '00000',
            'mobile2' => '00000',
            'mobile3' => '00000',
            'email' => 'abcd@gmail.com',
            'password' => Hash::make(123456),
            'vca_certificate' => 0,
            'own_car' => 0,
            'function_id' => 2,
            'id_type' => 'ssss',
            'id_number' => 'ssss',
            'id_expiry' => '2023-02-02',
            'nationality' => 'USA',
            'address' => 'USA',
            'postcode' => '02',
            'city' => 'NYC',
            'employ_agency_id' => 2,
            'employment_agency_note' => 'Nothing',
            'rate_per_hour' => '200',
            'cost_per_hour' => '10',
            'personnel_dates' => '2023-01-01',
            'active' => 0,
        ]);

        Personnel::create([
            'salutation' => 'Mr',
            'initials' => 'al',
            'first_name' => 'Ahmad',
            'last_name' => 'Raza',
            'dob' => '2023-01-01',
            'social_security_number' => '618',
            'date_service' => '2023-01-01',
            'telephone' => '090078601',
            'mobile' => '00000',
            'mobile2' => '00000',
            'mobile3' => '00000',
            'email' => 'abcd@gmail.com',
            'password' => Hash::make(123456),
            'vca_certificate' => 0,
            'own_car' => 0,
            'function_id' => 3,
            'id_type' => 'ssss',
            'id_number' => 'ssss',
            'id_expiry' => '2023-02-02',
            'nationality' => 'USA',
            'address' => 'USA',
            'postcode' => '02',
            'city' => 'NYC',
            'employ_agency_id' => 3,
            'employment_agency_note' => 'Nothing',
            'rate_per_hour' => '200',
            'cost_per_hour' => '10',
            'personnel_dates' => '2023-01-01',
            'active' => 1,
        ]);

        Personnel::create([
            'salutation' => 'Mr',
            'initials' => 'al',
            'first_name' => 'Sami',
            'last_name' => 'Sami',
            'dob' => '2023-01-01',
            'social_security_number' => '6548',
            'date_service' => '2023-01-01',
            'telephone' => '090078601',
            'mobile' => '00000',
            'mobile2' => '00000',
            'mobile3' => '00000',
            'email' => 'abcd@gmail.com',
            'password' => Hash::make(123456),
            'vca_certificate' => 0,
            'own_car' => 0,
            'function_id' => 4,
            'id_type' => 'ssss',
            'id_number' => 'ssss',
            'id_expiry' => '2023-02-02',
            'nationality' => 'USA',
            'address' => 'USA',
            'postcode' => '02',
            'city' => 'NYC',
            'employ_agency_id' => 4,
            'employment_agency_note' => 'Nothing',
            'rate_per_hour' => '200',
            'cost_per_hour' => '10',
            'personnel_dates' => '2023-01-01',
            'active' => 0,
        ]);

        Personnel::create([
            'salutation' => 'Mr',
            'initials' => 'al',
            'first_name' => 'Umer',
            'last_name' => 'Shareef',
            'dob' => '2023-01-01',
            'social_security_number' => '4448877',
            'date_service' => '2023-01-01',
            'telephone' => '090078601',
            'mobile' => '00000',
            'mobile2' => '00000',
            'mobile3' => '00000',
            'email' => 'abcd@gmail.com',
            'password' => Hash::make(123456),
            'vca_certificate' => 0,
            'own_car' => 0,
            'function_id' => 5,
            'id_type' => 'ssss',
            'id_number' => 'ssss',
            'id_expiry' => '2023-02-02',
            'nationality' => 'USA',
            'address' => 'USA',
            'postcode' => '02',
            'city' => 'NYC',
            'employ_agency_id' => 5,
            'employment_agency_note' => 'Nothing',
            'rate_per_hour' => '200',
            'cost_per_hour' => '10',
            'personnel_dates' => '2023-01-01',
            'active' => 1,
        ]);
    }
}
